apiVersion: apps/v1
kind: Deployment
metadata:
  name: cam-api-gateway
spec:
  #replicas: 3
  selector:
    matchLabels:
      app: cam-api-gateway
      tier: frontend
  template:
    metadata:
      labels:
        app: cam-api-gateway
        tier: frontend
        CI_COMMIT_REF_SLUG: {{ .Values.CI_COMMIT_REF_SLUG }}
        CI_COMMIT_SHA: {{ .Values.CI_COMMIT_SHA }}
    spec:
      containers:
        - name: cam-api-gateway
          image: registry.gitlab.eclipse.org/eclipse/xfsc/cam/cam-api-gateway:{{ .Values.tag }}
          imagePullPolicy: Always
          envFrom: [ configMapRef: { name: cam-config } ]
          env:
            - name: CAM_OAUTH2_DASHBOARD_AUTHORITY
              value: {{ .Values.services.apiGateway.oauth2.authority }}
            - name: CAM_OAUTH2_DASHBOARD_CLIENT_ID
              value: {{ .Values.services.apiGateway.oauth2.clientID }}
            - name: CAM_OAUTH2_DASHBOARD_REDIRECT_URI
              value: {{ .Values.services.apiGateway.oauth2.redirectURI }}
            - name: CAM_OAUTH2_DASHBOARD_POST_LOGOUT_REDIRECT_URI
              value: {{ .Values.services.apiGateway.oauth2.postLogoutRedirectURI }}
          ports:
            - containerPort: 8080
#          targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cam-api-gateway
  labels:
    app: cam-api-gateway
    tier: frontend
spec:
  #type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: cam-api-gateway
    tier: frontend
