name: Docker and Helm

on:
  release:
    types: [published]
  workflow_dispatch:
  
jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build Dashboard
        run: | 
            pushd dashboard
            npm install  && npm run build
            popd
      - name: Go Build
        run: |
            go build cmd/cam-api-gateway/cam-api-gateway.go
            go build cmd/cam-collection-authsec/cam-collection-authsec.go
            go build cmd/cam-collection-integrity/cam-collection-integrity.go
            go build cmd/cam-collection-workload/cam-collection-workload.go
            go build cmd/cam-eval-manager/cam-eval-manager.go
            go build cmd/cam-req-manager/cam-req-manager.go


  dockerbuild:
    needs: prebuild
    strategy:
      matrix:
        service: [  cam-api-gateway,
                    cam-collection-authsec,
                    cam-collection-commsec,
                    cam-collection-integrity,
                    cam-collection-workload,
                    cam-eval-manager,
                    cam-req-manager]
    uses: eclipse-xfsc/dev-ops/.github/workflows/dockerbuild.yml@main
    secrets: inherit
    with: 
      build_args: SERVICE=${{ matrix.service }}
      service: ${{ matrix.service }}
      dockerfile: "cmd/${SERVICE}/Dockerfile"